kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-storage
  namespace: itsmetommy
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
