# Specify permission
apiVersion: v1
kind: Pod
metadata:
  name: pod-03
  namespace: itsmetommy
  labels:
    app: secret-examples
spec:
  containers:
  - name: pod-03
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      defaultMode: 0400
